import {
  Building2,
  Library,
  FlaskConical,
  Monitor,
  Bus,
  HeartPulse,
  Music,
  Dumbbell,
  Wifi,
  Video,
  ShieldCheck,
} from 'lucide-react';

export interface Facility {
  id: string;
  title: string;
  icon: React.ElementType;
  description: string;
  detailedDescription: string;
  features?: string[];
  images: string[];
  color: string;
  bgColor: string;
}

export const facilitiesData: Facility[] = [
  {
    id: 'infrastructure',
    title: 'Infrastructure',
    icon: Building2,
    description: 'World-class infrastructure with modern amenities',
    detailedDescription: 'At SSRVM, we aim for a perfect balance of complementing facts: ancient and advanced, Indian and international, traditional and innovative. The School building campus is centrally air-conditioned and has a unique architectural design, state-of-the-art furniture and furnishings, an elegant reception hall, specialist studios for computer education and science, visual and performing arts.',
    features: [
      'Centrally Air-conditioned Campus',
      'Unique Architectural Design',
      'State-of-the-art Furniture',
      'Elegant Reception Hall',
      'Specialist Studios',
    ],
    images: [
      '/images/facilities/infrastructure1.jpg',
      '/images/facilities/infrastructure2.jpg',
    ],
    color: 'from-blue-600 to-indigo-600',
    bgColor: 'bg-blue-50',
  },
  {
    id: 'main-building',
    title: 'Main School Building',
    icon: Building2,
    description: 'Gyan Sarovar - The main school building',
    detailedDescription: 'Gyan Sarovar, the main school building, is a symbol of excellence and learning. It houses spacious classrooms, administrative offices, and specialized learning spaces. The building is designed to provide a conducive environment for learning with natural light, proper ventilation, and modern amenities.',
    features: [
      'Spacious Classrooms',
      'Administrative Offices',
      'Specialized Learning Spaces',
      'Natural Light & Ventilation',
      'Modern Amenities',
    ],
    images: [
      '/images/facilities/main1.jpg',
      '/images/facilities/main2.jpg',
      '/images/facilities/main3.jpg',
    ],
    color: 'from-purple-600 to-pink-600',
    bgColor: 'bg-purple-50',
  },
  {
    id: 'library',
    title: 'Library',
    icon: Library,
    description: 'Digital e-library with vast collection of books',
    detailedDescription: 'Our library is a treasure trove of knowledge with a vast collection of books, journals, and digital resources. The digital e-library provides students with access to online resources, e-books, and research materials. The library is designed to foster a love for reading and independent learning.',
    features: [
      'Vast Collection of Books',
      'Digital E-Library',
      'Online Resources',
      'E-Books & Journals',
      'Reading & Research Areas',
    ],
    images: [
      '/images/facilities/library1.jpg',
      '/images/facilities/library2.jpg',
      '/images/facilities/library3.jpg',
    ],
    color: 'from-green-600 to-emerald-600',
    bgColor: 'bg-green-50',
  },
  {
    id: 'laboratories',
    title: 'Laboratories',
    icon: FlaskConical,
    description: 'Well-equipped science laboratories',
    detailedDescription: 'Our science laboratories are equipped with modern equipment and facilities for Physics, Chemistry, and Biology. Students get hands-on experience with experiments and research projects. The labs are designed to ignite curiosity and foster scientific thinking.',
    features: [
      'Physics Laboratory',
      'Chemistry Laboratory',
      'Biology Laboratory',
      'Modern Equipment',
      'Safety Standards',
    ],
    images: [
      '/images/facilities/lab1.jpg',
      '/images/facilities/lab2.jpg',
      '/images/facilities/lab3.jpg',
    ],
    color: 'from-red-600 to-orange-600',
    bgColor: 'bg-red-50',
  },
  {
    id: 'computer-lab',
    title: 'Computer Lab',
    icon: Monitor,
    description: 'State-of-the-art computer laboratory',
    detailedDescription: 'The computer lab is equipped with the latest computers and software to prepare students for the digital age. Students learn programming, digital literacy, and various computer applications. The lab provides a platform for innovation and technological exploration.',
    features: [
      'Latest Computers',
      'High-speed Internet',
      'Programming Software',
      'Digital Literacy Programs',
      'Innovation Hub',
    ],
    images: [
      '/images/facilities/computer1.jpg',
      '/images/facilities/computer2.jpg',
      '/images/facilities/computer3.jpg',
    ],
    color: 'from-cyan-600 to-blue-600',
    bgColor: 'bg-cyan-50',
  },
  {
    id: 'smart-class',
    title: 'Smart Class',
    icon: Video,
    description: 'Technology-enabled smart classrooms',
    detailedDescription: 'Our smart classrooms are equipped with interactive whiteboards, projectors, and audio-visual systems that make learning engaging and interactive. Teachers use multimedia content to explain complex concepts, making learning a joyful experience.',
    features: [
      'Interactive Whiteboards',
      'Projectors & AV Systems',
      'Multimedia Content',
      'Engaging Learning',
      'Interactive Sessions',
    ],
    images: [
      '/images/facilities/smart1.jpg',
      '/images/facilities/smart2.jpg',
      '/images/facilities/smart3.jpg',
    ],
    color: 'from-teal-600 to-cyan-600',
    bgColor: 'bg-teal-50',
  },
  {
    id: 'transport',
    title: 'Transport System',
    icon: Bus,
    description: 'Air conditioned & GPS enabled transport',
    detailedDescription: 'Our transport system ensures safe and comfortable travel for students. All buses are air-conditioned and equipped with GPS tracking for real-time monitoring. Trained drivers and attendants ensure the safety of students during transit.',
    features: [
      'Air-conditioned Buses',
      'GPS Tracking',
      'Real-time Monitoring',
      'Trained Drivers',
      'Safety Protocols',
    ],
    images: [
      '/images/facilities/transport1.jpg',
      '/images/facilities/transport2.jpg',
      '/images/facilities/transport3.jpg',
    ],
    color: 'from-amber-600 to-yellow-600',
    bgColor: 'bg-amber-50',
  },
  {
    id: 'medical',
    title: 'Medical Facility',
    icon: HeartPulse,
    description: '24x7 medical facility for students',
    detailedDescription: 'We have a well-equipped medical facility with a qualified nurse and doctor on call. Regular health check-ups are conducted for all students. The medical room is equipped to handle emergencies and provide first aid when needed.',
    features: [
      'Qualified Nurse',
      'Doctor on Call',
      'Regular Health Check-ups',
      'Emergency Care',
      'First Aid Facility',
    ],
    images: [
      '/images/facilities/medical1.jpg',
      '/images/facilities/medical2.jpg',
      '/images/facilities/medical3.jpg',
    ],
    color: 'from-rose-600 to-red-600',
    bgColor: 'bg-rose-50',
  },
  {
    id: 'security',
    title: 'Safety & Security',
    icon: ShieldCheck,
    description: 'CCTV enabled campus with security protocols',
    detailedDescription: 'Student safety is our top priority. Our campus is equipped with CCTV cameras at all strategic locations. We have trained security personnel, visitor management systems, and strict safety protocols to ensure a secure learning environment.',
    features: [
      'CCTV Surveillance',
      'Trained Security Personnel',
      'Visitor Management',
      'Safety Protocols',
      'Emergency Response',
    ],
    images: [
      '/images/facilities/security1.jpg',
      '/images/facilities/security2.jpg',
      '/images/facilities/security3.jpg',
    ],
    color: 'from-slate-600 to-gray-600',
    bgColor: 'bg-slate-50',
  },
  {
    id: 'playground',
    title: 'Playground',
    icon: Dumbbell,
    description: 'Spacious playground for sports activities',
    detailedDescription: 'Our spacious playground provides ample space for various outdoor sports and physical activities. Students can enjoy football, cricket, basketball, athletics, and many other sports. The playground is maintained to the highest standards for safety and enjoyment.',
    features: [
      'Football Ground',
      'Cricket Pitch',
      'Basketball Court',
      'Athletics Track',
      'Safety Standards',
    ],
    images: [
      '/images/facilities/playground1.jpg',
      '/images/facilities/playground2.jpg',
      '/images/facilities/playground3.jpg',
    ],
    color: 'from-lime-600 to-green-600',
    bgColor: 'bg-lime-50',
  },
  {
    id: 'dance',
    title: 'Dance & Music',
    icon: Music,
    description: 'Indian & Western dance and music facilities',
    detailedDescription: 'We have dedicated studios for Indian and Western dance and music. Students learn various dance forms and musical instruments from trained professionals. Regular performances and competitions provide opportunities to showcase talent.',
    features: [
      'Dance Studios',
      'Music Rooms',
      'Indian & Western Dance',
      'Vocal & Instrumental Music',
      'Performance Opportunities',
    ],
    images: [
      '/images/facilities/dance1.jpg',
      '/images/facilities/dance2.jpg',
      '/images/facilities/dance3.jpg',
    ],
    color: 'from-fuchsia-600 to-pink-600',
    bgColor: 'bg-fuchsia-50',
  },
  {
    id: 'wifi',
    title: 'Wi-Fi Enabled Campus',
    icon: Wifi,
    description: 'High-speed Wi-Fi across the campus',
    detailedDescription: 'Our entire campus is Wi-Fi enabled, providing students and teachers with high-speed internet access. This supports digital learning, research, and connectivity. The Wi-Fi network is secure and monitored for safe usage.',
    features: [
      'High-speed Internet',
      'Campus-wide Coverage',
      'Secure Network',
      'Digital Learning Support',
      'Safe Usage Policy',
    ],
    images: [
      '/images/facilities/wifi1.jpg',
      '/images/facilities/wifi2.jpg',
      '/images/facilities/wifi3.jpg',
    ],
    color: 'from-indigo-600 to-blue-600',
    bgColor: 'bg-indigo-50',
  },
];